// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NETCourse1920_Nhom46.Models;

namespace NETCourse1920_Nhom46.Migrations
{
    [DbContext(typeof(QuanLyDbContext))]
    [Migration("20191130022623_createDB")]
    partial class createDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NETCourse1920_Nhom46.Models.KetQuaHocTap", b =>
                {
                    b.Property<int>("MaKQHT")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaLHP");

                    b.Property<int>("MaSV");

                    b.HasKey("MaKQHT");

                    b.HasIndex("MaLHP");

                    b.HasIndex("MaSV");

                    b.ToTable("KetQuaHocTaps");
                });

            modelBuilder.Entity("NETCourse1920_Nhom46.Models.Khoa", b =>
                {
                    b.Property<int>("MaKhoa")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenKhoa");

                    b.HasKey("MaKhoa");

                    b.ToTable("Khoas");
                });

            modelBuilder.Entity("NETCourse1920_Nhom46.Models.LopHocPhan", b =>
                {
                    b.Property<int>("MaLHP")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("DiemCuoiKy");

                    b.Property<double>("DiemGK");

                    b.Property<string>("HocKy");

                    b.Property<int>("MaMon");

                    b.Property<string>("NamHoc");

                    b.HasKey("MaLHP");

                    b.HasIndex("MaMon");

                    b.ToTable("LopHocPhans");
                });

            modelBuilder.Entity("NETCourse1920_Nhom46.Models.MonHoc", b =>
                {
                    b.Property<int>("MaMon")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SoTinChi");

                    b.Property<string>("TenMon");

                    b.HasKey("MaMon");

                    b.ToTable("MonHocs");
                });

            modelBuilder.Entity("NETCourse1920_Nhom46.Models.SinhVien", b =>
                {
                    b.Property<int>("MaSV")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DienThoai");

                    b.Property<string>("HoTen");

                    b.Property<int>("MaKhoa");

                    b.Property<int>("MaLHP");

                    b.Property<DateTime>("NgaySinh");

                    b.HasKey("MaSV");

                    b.HasIndex("MaKhoa");

                    b.HasIndex("MaLHP");

                    b.ToTable("SinhViens");
                });

            modelBuilder.Entity("NETCourse1920_Nhom46.Models.KetQuaHocTap", b =>
                {
                    b.HasOne("NETCourse1920_Nhom46.Models.LopHocPhan", "LopHocPhan")
                        .WithMany()
                        .HasForeignKey("MaLHP")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NETCourse1920_Nhom46.Models.SinhVien", "SinhVien")
                        .WithMany()
                        .HasForeignKey("MaSV")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NETCourse1920_Nhom46.Models.LopHocPhan", b =>
                {
                    b.HasOne("NETCourse1920_Nhom46.Models.MonHoc", "MonHoc")
                        .WithMany("LopHocPhans")
                        .HasForeignKey("MaMon")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NETCourse1920_Nhom46.Models.SinhVien", b =>
                {
                    b.HasOne("NETCourse1920_Nhom46.Models.Khoa", "Khoa")
                        .WithMany("SinhViens")
                        .HasForeignKey("MaKhoa")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NETCourse1920_Nhom46.Models.LopHocPhan", "LopHocPhan")
                        .WithMany("SinhViens")
                        .HasForeignKey("MaLHP")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
